[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "yuhi"
dynamic = ["version"]
description = "Python CLI toolkit to automate project enhancement using standard config templates."
readme = "README.md"
authors = [
    { name = "Rishabh B", email = "null@example.com" }
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
]
keywords = ["yuhi", "project", "boilerplate"]
dependencies = ["click", "httpx", "questionary", "ruamel.yaml~=0.18.10"]
requires-python = ">=3.11"

[dependency-groups]
build = ["build", "twine"]
lint = ["pre-commit", "t-run"]
test = ["pytest", "pytest-cov"]

[project.scripts]
yuhi = "src.cli:cli"

[project.urls]
Docs = "https://yuhi.readthedocs.io/"
Repository = "https://github.com/rsb-23/yuhi"
Issues = "https://github.com/rsb-23/yuhi/issues"
Releases = "https://github.com/rsb-23/yuhi/releases"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = ["src", "templates", "samples"]

[tool.pylint]
jobs = 2
ignore-paths = ["^(?!^(src|tests?|.+.py)$).+$"]
max-line-length = 130

[tool.pylint.messages_control]
disable = [
    "I",
    "import-error",
    "fixme",
    "missing-docstring",
    "duplicate-code",
    "no-name-in-module",
    "too-few-public-methods"
]

[tool.coverage.report]
fail_under = 80.0
[tool.coverage.run]
source = ["src/"]
