name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: rsb-23/actions/checkout@main
        with:
          fetch-tags: true

      - name: Set up Python
        uses: rsb-23/actions/setup-python@main
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --group build

      - name: Build package
        run: python -m build && twine check dist/*

      - name: Upload build artifact
        uses: actions/upload-artifact@v7.0.2
        with:
          name: dist
          path: dist/
          retention-days: 7

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Download build
        uses: actions/download-artifact@v8.0.2
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.14.2

  gh-release:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          gh release create "$TAG" --generate-notes --repo "$GITHUB_REPOSITORY"

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions: { }
