name: Test Setup
description: 'Test setup action for this project'

inputs:
  python-version:
    required: true
    description: "py version"

runs:
  using: "composite"
  steps:
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5.1.1
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
    - name: Installing test deps...
      run: |
        python -m pip install --upgrade pip
        pip install '.[test]'
      shell: bash
