name: Code Lint
on:
  pull_request:
    types: [ reopened ]
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.11
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[ lint ]'
          pre-commit install

      - name: Run pre-commit
        env:
          SKIP: mypy, pylint, no-commit-to-branch
        run: pre-commit run --all-files
