name: Unit Tests

on:
  pull_request:
    types: [ reopened ]
  push:

env:
  PY_BASE_VERSION: "3.11"

jobs:
  coverage-test: # Tests code for base version and coverage
    runs-on: windows-latest
    steps:
      - &checkout
        uses: rsb-23/actions/checkout@main
      - uses: &test-runner rsb-23/actions/test-runner@main
        with:
          python-version: ${{ env.PY_BASE_VERSION }}
          coverage: true

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: coverage-report
          path: coverage.xml

  macos-test: # Tests on macOS latest
    needs: coverage-test
    runs-on: macos-latest
    steps:
      - *checkout
      - uses: *test-runner
        with:
          python-version: ${{ env.PY_BASE_VERSION }}

  version-tests: # Tests code for higher version in ubuntu
    needs: coverage-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12", "3.13", "3.14", "3.15.0-rc.3" ]
    steps:
      - *checkout
      - uses: *test-runner
        with:
          python-version: ${{ matrix.python-version }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: { }
